### ISSUE TITLE
Remove all IDE-related files from the repository

### ISSUE THREAD

**Issue by safeyhalim** [safeyhalim/guratorproject#20]
Remove the unnecessary files from the repository and add their extensions to relevant .gitignore files

**Comment by Nightz12** [comment]
got specific files in mind, because the only one i see, that is no longer required is the yelp.json file

**Comment by safeyhalim** [comment]
Looks like this commit: https://github.com/safeyhalim/guratorproject/commit/f72163ed2e185e037f90be145bd06312a487ae1e
solved the issue with .idea file(s). I will close this ticket.
