### ISSUE TITLE
Student should be a member of one internal group and one external group 

### ISSUE THREAD

**Issue by safeyhalim** [safeyhalim/guratorproject#25]
Group size should be at least 3.
Student should be a member of one internal group.
And he/she should create an external group

**Comment by Nightz12** [comment]
I stated on the group creation page, that they should do that and labeled every group as in or external
Is that enough, or how do you intend on "forcing" them to do that

**Comment by safeyhalim** [comment]
That's enough. It's okay to rely on students understanding
